### ISSUE TITLE
ambiguously suggest a height of zero

### ISSUE THREAD

**Issue by delphswiftier** [xmartlabs/XLForm#718] opened 2016-01-30 16:18 UTC
In formRowDescriptorValueHasChanged I'm checking row tag and value like this
if formRow.tag == "marketEnabled" {
          if let text = formRow.value where text as! String == "enabled" {
//few repeats of creating row and adding via form.addFormRow here

So it looks like the section expands. on this action I'm getting this error:

2016-01-30 19:14:24.044 XLFormTests[18342:11002416] Warning once only: Detected a case where constraints ambiguously suggest a height of zero for a tableview cell's content view. We're considering the collapse unintentional and using standard height instead.

**Comment by sumowesley** [comment] 2016-01-31 16:00
Possible duplicate of #494?

**Closed** 2016-05-30 21:10 UTC
Labels: duplicate
