### ISSUE TITLE
Decimal Precision Errors in XLFormTextFieldCell

### ISSUE THREAD

**Issue by cbh2000** [xmartlabs/XLForm#580] opened 2015-09-25 20:24 UTC
Try typing in `8.14` into a decimal field, and you will see it become `8.14000000000001`. This is because floats and doubles aren't precise enough to represent 8.14 perfectly.

Some ideas:
- Change the underlying type to NSDecimalNumber or NSString
- Add support for "max decimal places" or rounding

**Comment by jeanmartin** [comment] 2016-06-27 13:37
How is this a feature request and not a bug? Also, I could not find the 'duplicate' of this, could somebody point me to it?

**Comment by mats-claassen** [comment] 2016-06-27 16:30
In fact this should be fixed already... Did you have this problem with the latest version?

**Comment by jeanmartin** [comment] 2016-06-27 18:23
Ah, just upgraded and can confirm: it is fixed 👍

**Closed** 2016-06-28 12:46 UTC
Labels: duplicate, feature request
