### ISSUE TITLE
How can I modify the XLFormViewController_ValidationErrorTitle? 

### ISSUE THREAD

**Issue by JorgeAGomez** [xmartlabs/XLForm#815] opened 2016-06-30 21:38 UTC
How can I change the "XLFormViewController_ValidationErrorTitle" for something more appropiate? 

How can I change that title? 

This is what I have for the first row which takes the first name:
   
`//First name`
    `personalInformationRow = [XLFormRowDescriptor formRowDescriptorWithTag:@"First name" rowType:XLFormRowDescriptorTypeText title:@"First name"];`
  `  personalInformationRow.required = YES;`
  `  personalInformationRow.requireMsg = @"First name cannot be empty";`
  `  [personalInfomartionSection addFormRow:personalInformationRow];`

<img width="573" alt="screenshot 2016-06-30 15 37 47" src="https://cloud.githubusercontent.com/assets/6026875/16505090/a1b6f882-3ed8-11e6-92ec-bf4fe23ecfe5.png">

**Comment by sumowesley** [comment] 2016-07-02 20:49
Is this a duplicate of #396?

**Comment by mats-claassen** [comment] 2016-07-07 14:00
Yes seems so.

**Closed by mats-claassen** 2016-07-07 14:00 UTC
