### ISSUE TITLE
[iOS 9] Table view not pinned to top layout guide

### ISSUE THREAD

**Issue by chrisballinger** [xmartlabs/XLForm#561] opened 2015-09-16 23:41 UTC
The table view contents are underneath the nav bar on iOS 9:

![simulator screen shot sep 16 2015 4 41 09 pm](https://cloud.githubusercontent.com/assets/518687/9921387/c68dac70-5c91-11e5-8b6c-e4ebcf5ba80c.png)

**Comment by adrianmacneil** [comment] 2015-09-17 00:18
+1

**Comment by adrianmacneil** [comment] 2015-09-17 00:19
Dupe of #519

**Comment by adrianmacneil** [comment] 2015-09-17 00:23
See https://github.com/xmartlabs/XLForm/issues/483#issuecomment-138707904 for a simpler workaround

**Comment by adil-appifytech** [comment] 2015-09-20 17:49
@adrianmacneil - That fix is not working. It add extra 20 points (at-least that's in my case).

**Comment by adrianmacneil** [comment] 2015-09-20 19:25
That looks like the default (correct) padding to me. Can you add a screenshot from iOS 8?

**Comment by adil-appifytech** [comment] 2015-09-21 02:26
@adrianmacneil - But what if I don't want any padding? Issue with this padding is that when I select "Frequency Text Field", it don't scroll the tableview up. I will download iOS 8 simulator later and check it there too.

**Comment by adil-appifytech** [comment] 2015-09-21 10:55
@adrianmacneil  - I checked on iOS 8 device with XCode 7.0 and same issue.

**Closed** 2015-11-13 03:22 UTC
Labels: answered, duplicate
